
apis:
  main@v1: ./openapi/openapi.yaml
    root: ./openapi/openapi.yaml
styleguide:
  rules:
    no-invalid-media-type-examples: error
theme.openapi:
  pagination: section
  showConsole: true
  theme:
    menu:
      backgroundColor: '#fffff'
