
apis:
  main@v1: ./openapi/openapi.yaml
  root: ./openapi/openapi.yaml
  rules:
    no-invalid-media-type-examples: error
    allowAdditionalProperties: true
theme.openapi:
  pagination: section
  showConsole: true
  theme:
    openapi: {}
    mockServer: {}
  menu:
  backgroundColor: '#fffff'
